[package]
name = "find-similar-images"
version = "0.1.0"
authors = ["relievedFace <relievedFace@gmaile.com>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = "2.33.0"
rayon = "1.2.1"
image = "0.22.3"
itertools = "0.9.0"
